name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  update-build-version:
    runs-on: ubuntu-latest
    environment: .env.production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Build Version
        run: echo "BUILD_VERSION=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Print Variable
        run: echo "Build version is $BUILD_VERSION"

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Authenticate with GitHub CLI
        run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token

      - name: Update GitHub Environment Variable
        run: |
          gh api \
          --method PUT \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/environments/.app.production/secrets/BUILD_VERSION \
            -f encrypted_value="${BUILD_VERSION}"

  deploy:
    runs-on: ubuntu-latest
    environment: .env.production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.14.0'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}

        run: |
          echo "${SSH_PRIVATE_KEY}" > private_key.pem
          chmod 400 private_key.pem
          openssl rsa -in private_key.pem -text -noout

          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'

            cd /etc
    
            echo "HOST=${{ secrets.EC2_HOST }}" > app.env
            echo "USER=${{ secrets.EC2_USER }}" >> app.env
            echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> app.env
            echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}" >> app.env
            echo "BUCKET_REGION=${{ secrets.BUCKET_REGION }}" >> app.env
            echo "ACCESS_KEY=${{ secrets.ACCESS_KEY }}" >> app.env
            echo "SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS_KEY }}" >> app.env
            echo "PORT=${{ secrets.PORT }}" >> app.env
            echo "DB_URI=${{ secrets.DB_URI }}" >> app.env
            echo "SALT_WORK_FACTOR=${{ secrets.SALT_WORK_FACTOR }}" >> app.env
            echo "ACCESS_TOKEN_TTL=${{ secrets.ACCESS_TOKEN_TTL }}" >> app.env
            echo "REFRESH_TOKEN_TTL=${{ secrets.REFRESH_TOKEN_TTL }}" >> app.env
            echo "ORIGIN=${{ secrets.ORIGIN }}" >> app.env
            echo "S3_BUCKET_URL=${{ secrets.S3_BUCKET_URL }}" >> app.env
            echo "DOMAIN=${{ secrets.DOMAIN }}" >> app.env
            echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> app.env
            echo "PUBLIC_KEY=${{ secrets.PUBLIC_KEY }}" >> app.env
            echo "SES_ACCESS_KEY=${{ secrets.SES_ACCESS_KEY }}" >> app.env
            echo "SES_SECRET_ACCESS_KEY=${{ secrets.SES_SECRET_ACCESS_KEY }}" >> app.env
            echo "SES_EMAIL_SOURCE=${{ secrets.SES_EMAIL_SOURCE }}" >> app.env 

            chmod 600 app.env
            sudo chown ubuntu:ubuntu app.env

            cd /home/ubuntu/sg_server
            git pull origin main
            npm install
            npm run build
            sudo systemctl restart myapp.service
          EOF
